version: "1"

# https://javatodev.com/docker-compose-for-spring-boot-with-mongodb/
# https://www.mongodb.com/compatibility/docker
# https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    volumes:
      # https://stackoverflow.com/questions/40905761/how-do-i-mount-a-host-directory-as-a-volume-in-docker-compose
      - ./backend/decompiled_sources:/app/decompiled_sources

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - 8000:8000

  mongodb:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

